/* AUTO-GENERATED by scripts/build-gallery.js. Do not edit by hand. */
window.GALLERY = {
  "categories": [
    {
      "key": "curtains",
      "label": "Curtains",
      "photos": [
        {
          "src": "images/gallery/curtains/curtain.jpg",
          "title": "Curtain"
        },
        {
          "src": "images/gallery/curtains/Curtain_Blind2.jpg",
          "title": "Curtain Blind2"
        },
        {
          "src": "images/gallery/curtains/Curtain_Blind3.jpg",
          "title": "Curtain Blind3"
        },
        {
          "src": "images/gallery/curtains/Curtain_Blind4.jpg",
          "title": "Curtain Blind4"
        },
        {
          "src": "images/gallery/curtains/Curtain_Blind5.jpg",
          "title": "Curtain Blind5"
        },
        {
          "src": "images/gallery/curtains/Curtain_Blind6.jpg",
          "title": "Curtain Blind6"
        }
      ],
      "videos": []
    },
    {
      "key": "roller",
      "label": "Roller blinds",
      "photos": [
        {
          "src": "images/gallery/roller/roller.jpg",
          "title": "Roller"
        },
        {
<<<<<<< HEAD
=======
          "src": "images/gallery/roller/roller_blind7.jpg",
          "title": "Roller blind7"
        },
        {
          "src": "images/gallery/roller/roller_blind2.jpg",
          "title": "Roller blind2"
        },
        {
          "src": "images/gallery/roller/roller_blind3.jpg",
          "title": "Roller blind3"
        },
        {
>>>>>>> 7dd5b3c (Complete update)
          "src": "images/gallery/roller/roller_blind4.jpg",
          "title": "Roller blind4"
        },
        {
          "src": "images/gallery/roller/roller_blind5.jpg",
          "title": "Roller blind5"
        },
        {
          "src": "images/gallery/roller/roller_blind6.jpg",
          "title": "Roller blind6"
<<<<<<< HEAD
        },
        {
          "src": "images/gallery/roller/roller_blind7.jpg",
          "title": "Roller blind7"
        },
        {
          "src": "images/gallery/roller/roller_blind2.jpg",
          "title": "Roller blind2"
        },
        {
          "src": "images/gallery/roller/roller_blind3.jpg",
          "title": "Roller blind3"
=======
>>>>>>> 7dd5b3c (Complete update)
        }
      ],
      "videos": []
    },
    {
      "key": "roman",
      "label": "Roman blinds",
      "photos": [
        {
          "src": "images/gallery/roman/roman.jpg",
          "title": "Roman"
        }
      ],
      "videos": []
    },
    {
      "key": "film",
      "label": "Sun control and decorative film",
      "photos": [
        {
          "src": "images/gallery/film/film.jpg",
          "title": "Film"
        }
      ],
      "videos": []
    },
    {
      "key": "monsoon",
      "label": "Monsoon",
      "photos": [
        {
          "src": "images/gallery/monsoon/monsoon.jpg",
          "title": "Monsoon"
        }
      ],
      "videos": []
    },
    {
      "key": "wooden",
      "label": "Wooden",
      "photos": [
        {
          "src": "images/gallery/wooden/wooden.jpg",
          "title": "Wooden"
        },
        {
          "src": "images/gallery/wooden/Wooden_Blind_5.jpg",
          "title": "Wooden Blind"
        },
        {
          "src": "images/gallery/wooden/wooden_blind1.jpg",
          "title": "Wooden blind1"
        },
        {
          "src": "images/gallery/wooden/wooden_blind3.jpg",
          "title": "Wooden blind3"
        },
        {
          "src": "images/gallery/wooden/wooden_blind4.jpg",
          "title": "Wooden blind4"
        }
      ],
      "videos": []
    }
  ],
<<<<<<< HEAD
  "products": {}
=======
  "products": {
    "chick": "images/products/chick.jpg?v=bbf775cb",
    "curtains": "images/products/curtains.jpg?v=a7e146de",
    "film": "images/products/film.jpg?v=0dd435e0",
    "roller": "images/products/roller.jpg?v=09a35d70",
    "roman": "images/products/roman.jpg?v=bd92ba92"
  }
>>>>>>> 7dd5b3c (Complete update)
};
