/* AUTO-GENERATED by scripts/build-gallery.js. Do not edit by hand. */
window.GALLERY = {
  "categories": [
    {
      "key": "roller",
      "label": "Roller blinds",
      "photos": [
        {
          "src": "images/gallery/roller/roller_blind1.jpg",
          "title": "Roller blind1"
        },
        {
          "src": "images/gallery/roller/roller_blind2.jpg",
          "title": "Roller blind2"
        },
        {
          "src": "images/gallery/roller/roller_blind3.jpg",
          "title": "Roller blind3"
        },
        {
          "src": "images/gallery/roller/roller_blind4.jpg",
          "title": "Roller blind4"
        },
        {
          "src": "images/gallery/roller/roller_blind5.jpg",
          "title": "Roller blind5"
        },
        {
          "src": "images/gallery/roller/roller_blind6.jpg",
          "title": "Roller blind6"
        }
      ],
      "videos": []
    },
    {
      "key": "monsoon",
      "label": "Monsoon",
      "photos": [
        {
          "src": "images/gallery/monsoon/monsoon_blind1.jpg",
          "title": "Monsoon blind1"
        }
      ],
      "videos": []
    },
    {
      "key": "wooden",
      "label": "Wooden",
      "photos": [
        {
          "src": "images/gallery/wooden/wooden_blind1.jpg",
          "title": "Wooden blind1"
        },
        {
          "src": "images/gallery/wooden/wooden_blind2.jpg",
          "title": "Wooden blind2"
        },
        {
          "src": "images/gallery/wooden/wooden_blind3.jpg",
          "title": "Wooden blind3"
        },
        {
          "src": "images/gallery/wooden/wooden_blind4.jpg",
          "title": "Wooden blind4"
        }
      ],
      "videos": []
    }
  ]
};
